### ISSUE TITLE
Info - Using your code

### ISSUE THREAD

**Issue by kidandcat** [codemasher/gw2api-tools#4]
Just want to warn you I'm using your location map embedded in a guild wars forum: http://galax.be

PD: you need to log to see the map, test user: prueba pass: pruebaprueba

Thanks for your codes!

**Comment by codemasher** [comment]
Hey, thanks for letting me know! I'm glad that someone found my code useful! :)

**Comment by Aspanfoot** [comment]
Thank u very much you are awesome)
